version: "3"
services:
    game-engine:
        image: coderone.azurecr.io/bomberland-engine:2381
        volumes:
            - type: "bind"
              source: ./agents/replay.json
              target: /app/replay.json

    python3-agent:
        build:
            context: agents/python3
            dockerfile: Dockerfile

    python3_1-agent:
        build:
            context: agents/python3_1
            dockerfile: Dockerfile

    python3_2-agent:
        build:
            context: agents/python3_2
            dockerfile: Dockerfile
        #    dockerfile: Dockerfile.dev # ra
        #volumes: # ra
        #    - ./agents/python3_2:/app #ra

    python3_3-agent:
        build:
            context: agents/python3_3
            dockerfile: Dockerfile
        #    dockerfile: Dockerfile.dev # ra
        #volumes: # ra
        #    - ./agents/python3_3:/app #ra

    python3_4-agent:
        build:
            context: agents/python3_4
            dockerfile: Dockerfile
        #    dockerfile: Dockerfile.dev # ra
        #volumes: # ra
        #    - ./agents/python3_4:/app #ra

    python3_5-agent:
        build:
            context: agents/python3_5
            dockerfile: Dockerfile
        #    dockerfile: Dockerfile.dev # ra
        #volumes: # ra
        #    - ./agents/python3_5:/app #ra

    beneficial_increase-agent:
        build:
            context: agents/beneficial_increase
            dockerfile: Dockerfile
            dockerfile: Dockerfile.dev # ra
        volumes: # ra
            - ./agents/beneficial_increase:/app #ra

    python3_7-agent:
        build:
            context: agents/python3_7
            dockerfile: Dockerfile
            dockerfile: Dockerfile.dev # ra
        volumes: # ra
            - ./agents/python3_7:/app #ra

    python3_8-agent:
        build:
            context: agents/python3_8
            dockerfile: Dockerfile
            dockerfile: Dockerfile.dev # ra
        volumes: # ra
            - ./agents/python3_8:/app #ra
